### ISSUE TITLE
Will 510.0.0 be released?

### ISSUE THREAD

**Issue by kkk669** [apple/swift-format#697]
[swift-5.10.0-RELEASE](https://github.com/apple/swift-format/releases/tag/swift-5.10-RELEASE) has been released recently, but it lacks various features and fixes that [509.0.0](https://github.com/apple/swift-format/releases/tag/509.0.0) had.

For example, it doesn't include https://github.com/apple/swift-format/pull/623.

So I'm wondering if 510.0.0 will be released with more changes than swift-5.10-RELEASE.

**Comment by allevato** [comment]
I'll be doing some cherry-picks into the 5.10 release branch before cutting a release. Expect this to happen in the next few days.

**Comment by allevato** [comment]
It's fine to leave it open to track the release.

**Comment by ahoppen** [comment]
I just pushed `510.0.0`: https://github.com/apple/swift-format/tree/510.0.0

**Comment by kkk669** [comment]
@ahoppen @allevato 

swift-format 510.0.0 is the same commit hash as swift-5.10-RELEASE, so it's still broken.

> I'll be doing some cherry-picks into the 5.10 release branch before cutting a release.

You didn't do that.

For example, swift-format 510.0.0 and 510.0.1 will format the following code:

```swift
let a = 0
print(consume a)
```

into

```swift
let a = 0
print(consumea)
```

swift-format 509.0.0 doesn't have this issue because it's already fixed in https://github.com/apple/swift-format/pull/623. swift-format 510.0.x doesn't include it.

**Comment by kkk669** [comment]
Thank you for sharing the detailed information. I agree with that way of proceeding.

**Comment by ahoppen** [comment]
I just tagged [510.1.0](https://github.com/apple/swift-format/releases/tag/510.1.0), which should contain the fixes that were present in `509.0.0` but not `510.0.1`
